
# SEO settings
title: "ash "
title2: " siddiqui" # default: ""
description: "mo data mo problems."
keywords: "data, science, machine, learning, blog, siddiqui, ashfaque, ash"
url: http://ausiddiqui.github.io/ # site url
# baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-91621138-1
repo: http://github.com/ausiddiqui
disqus_shortname: #"heiswayi"
twitter_username: "jaatah"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Ash Siddiqui"
  job      : "data analytics professional"
  bio      : ""
  thumb    : https://pbs.twimg.com/profile_images/829179497723240448/tn5WTxwJ_400x400.jpg
  email    : ausiddiqui@gmail.com
  url      : https://ausiddiqui.github.io
  github   : https://github.com/ausiddiqui
  twitter  : https://twitter.com/jaatah
  facebook :
  linkedin : https://linkedin.com/in/ausiddiqui

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@jaatah"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
